site_name: Al-waleed Shihadeh
site_description: Al-waleed Shihadeh
site_author: wshihadeh
site_url: https://wshihadeh.github.io
dev_addr: 0.0.0.0:8000

repo_name: 'GitHub'
repo_url: 'https://github.com/wshihadeh/wshihadeh.github.io'

docs_dir: 'content'
edit_uri: 'edit/source/docs/content/'

# https://squidfunk.github.io/mkdocs-material/
theme:
  name: 'material'
  custom_dir: 'theme'
  language: en
  include_sidebar: true
  #favicon: assets/img/icon.png
  #logo: assets/img/logo.png
  feature:
    tabs: false
  palette:
    primary: 'cyan'
    accent: 'cyan'
  i18n:
    prev: 'Previous'
    next: 'Next'

copyright: "Copyright &copy; 2016-2019 Al-waleed Shihadeh"

extra_css:
  - assets/styles/extra.css
  - assets/styles/atom-one-light.css # HightlightJS's CSS theme

extra_javascript:
  - assets/js/hljs/highlight.pack.js # Download from https://highlightjs.org/download/ and enable YAML, TOML and Dockerfile
  - assets/js/extra.js

plugins:
  - search
  - exclude:
      glob:
        - "**/include-*.md"

# https://squidfunk.github.io/mkdocs-material/extensions/admonition/
# https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      use_pygments: false # hljs is used instead of pygment for TOML highlighting support
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.snippets:
      check_paths: true
  - toc:
      permalink: true

# Page tree
nav:
  - 'Welcome': 'index.md'
  #- 'Ruby Gems':
  #    - 'Swarm Orca' : 'getting-started/concepts.md'
  #    - 'RabbitMQ Client' : 'getting-started/concepts.md'
  #    - 'RabbitMQ Client' : 'getting-started/concepts.md'
  #    - 'DelayedJob Metrics' : 'getting-started/concepts.md'
  #    - 'DeepHealthCheck': 'getting-started/concepts.md'
  #- 'Blog Posts':
  #- 'PoC':
